/* eslint-disable */
// Generates root-level .bat files as UTF-8 (no BOM) with CRLF line endings.
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');

const files = {
  'setup.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'setlocal',
    'set "ROOT=%~dp0"',
    'cd /d "%ROOT%"',
    '',
    'echo =====================================',
    'echo [setup] 白云学院校友平台 环境搭建',
    'echo =====================================',
    '',
    'echo [1/5] 检查 Node 版本 ...',
    'where node >nul 2>&1',
    'if errorlevel 1 (',
    '  echo [错误] 未检测到 Node.js，请先安装 Node 20.11+',
    '  exit /b 1',
    ')',
    'for /f "delims=" %%v in (\'node -v\') do set "NODE_VER=%%v"',
    'echo 当前 Node 版本：%NODE_VER%',
    'node -e "var v=process.versions.node.split(\'.\').map(Number);if(v[0]<20||(v[0]===20&&v[1]<11)){console.error(\'[错误] Node 版本过低，需要 >= 20.11\');process.exit(1)}"',
    'if errorlevel 1 exit /b 1',
    '',
    'echo [2/5] 启用 corepack ...',
    'call corepack enable',
    'if errorlevel 1 (',
    '  echo [警告] corepack enable 失败，将直接使用系统 pnpm',
    ')',
    '',
    'echo [3/5] 安装 pnpm 依赖 ...',
    'call pnpm install',
    'if errorlevel 1 exit /b 1',
    '',
    'echo [4/5] 构建 design-tokens（生成 CSS/Tailwind 变量）...',
    'call pnpm turbo run build --filter=@bynu/design-tokens',
    'if errorlevel 1 exit /b 1',
    '',
    'echo [5/5] 尝试生成 Prisma Client（若存在 schema）...',
    'if exist "%ROOT%packages\\db\\prisma\\schema.prisma" (',
    '  call pnpm --filter @bynu/db exec prisma generate',
    '  if errorlevel 1 echo [提示] prisma generate 失败或未安装 prisma CLI，已忽略',
    ') else (',
    '  echo [提示] 未检测到 packages/db/prisma/schema.prisma，跳过',
    ')',
    '',
    'echo =====================================',
    'echo [setup] 环境搭建完成',
    'echo 下一步：双击 start.bat 启动服务',
    'echo =====================================',
    'endlocal',
    'exit /b 0',
    '',
  ].join('\n'),

  'start.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'setlocal enabledelayedexpansion',
    'set "ROOT=%~dp0"',
    'cd /d "%ROOT%"',
    '',
    'echo =====================================',
    'echo [start] 启动白云学院校友平台',
    'echo =====================================',
    '',
    'if not exist "%ROOT%node_modules" (',
    '  echo [错误] 未检测到 node_modules，请先运行 setup.bat',
    '  exit /b 1',
    ')',
    '',
    'echo [1/3] 释放端口 3000 / 3001 / 5173 / 5174 ...',
    'for %%P in (3000 3001 5173 5174) do call :KILL_PORT %%P',
    '',
    'echo [2/3] 拉起子服务窗口 ...',
    'start "bynu-backend" cmd /k ""%ROOT%start-backend.bat""',
    'start "bynu-bff"     cmd /k ""%ROOT%start-bff.bat""',
    'start "bynu-web"     cmd /k ""%ROOT%start-web.bat""',
    '',
    'echo [3/3] 服务访问地址：',
    'echo   后端 NestJS  : http://localhost:3001',
    'echo   BFF Gateway  : http://localhost:3000',
    'echo   Admin Web    : http://localhost:5173',
    'echo.',
    'echo 子窗口已在后台启动，关闭对应窗口即可停止服务',
    'echo =====================================',
    'endlocal',
    'exit /b 0',
    '',
    ':KILL_PORT',
    'set "PORT=%~1"',
    'for /f "tokens=5" %%a in (\'netstat -ano ^| findstr ":%PORT% " ^| findstr "LISTENING"\') do (',
    '  echo   端口 %PORT% 被进程 %%a 占用，正在结束 ...',
    '  taskkill /PID %%a /F >nul 2>&1',
    ')',
    'goto :eof',
    '',
  ].join('\n'),

  'start-backend.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'cd /d "%~dp0"',
    'title bynu-backend (@bynu/server :3001)',
    'echo [backend] 启动 @bynu/server（NestJS @ 3001）...',
    'call pnpm --filter @bynu/server dev',
    'if errorlevel 1 (',
    '  echo [backend] 进程异常退出 errorlevel=%errorlevel%',
    '  pause',
    '  exit /b 1',
    ')',
    '',
  ].join('\n'),

  'start-bff.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'cd /d "%~dp0"',
    'title bynu-bff (@bynu/bff-gateway :3000)',
    'echo [bff] 启动 @bynu/bff-gateway（Fastify/BFF @ 3000）...',
    'call pnpm --filter @bynu/bff-gateway dev',
    'if errorlevel 1 (',
    '  echo [bff] 进程异常退出 errorlevel=%errorlevel%',
    '  pause',
    '  exit /b 1',
    ')',
    '',
  ].join('\n'),

  'start-web.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'cd /d "%~dp0"',
    'title bynu-web (@bynu/admin-web :5173)',
    'echo [web] 启动 @bynu/admin-web（Vite @ 5173）...',
    'call pnpm --filter @bynu/admin-web dev',
    'if errorlevel 1 (',
    '  echo [web] 进程异常退出 errorlevel=%errorlevel%',
    '  pause',
    '  exit /b 1',
    ')',
    '',
  ].join('\n'),

  'reimport.bat': [
    '@echo off',
    'chcp 65001 >nul',
    'setlocal enabledelayedexpansion',
    'set "ROOT=%~dp0"',
    'cd /d "%ROOT%"',
    '',
    'echo =====================================',
    'echo [reimport] 清空本地数据（sqlite / pglite）',
    'echo =====================================',
    'echo 将清理以下目录中的所有数据文件：',
    'echo   - apps\\server\\.data',
    'echo   - apps\\bff-gateway\\.data',
    'echo.',
    '',
    'set /p confirm=确认继续？输入 Y 继续，其他键取消: ',
    'if /i not "%confirm%"=="Y" (',
    '  echo 已取消',
    '  endlocal',
    '  exit /b 0',
    ')',
    '',
    'echo [1/2] 尝试释放可能占用数据文件的服务进程 ...',
    'for %%P in (3000 3001) do call :KILL_PORT %%P',
    '',
    'echo [2/2] 清理数据文件 ...',
    'for %%D in ("apps\\server\\.data" "apps\\bff-gateway\\.data") do (',
    '  set "TARGET=%ROOT%%%~D"',
    '  if exist "!TARGET!" (',
    '    echo 清理目录 %%~D ...',
    '    del /f /q /s "!TARGET!\\*.sqlite"  >nul 2>&1',
    '    del /f /q /s "!TARGET!\\*.sqlite3" >nul 2>&1',
    '    del /f /q /s "!TARGET!\\*.db"      >nul 2>&1',
    '    del /f /q /s "!TARGET!\\*.pglite"  >nul 2>&1',
    '    del /f /q /s "!TARGET!\\*.wal"     >nul 2>&1',
    '    del /f /q /s "!TARGET!\\*.shm"     >nul 2>&1',
    '    for /d %%S in ("!TARGET!\\*") do rmdir /s /q "%%S" 2>nul',
    '  ) else (',
    '    echo 目录不存在，跳过 %%~D',
    '  )',
    ')',
    '',
    'echo =====================================',
    'echo [reimport] 数据清理完成',
    'echo =====================================',
    'endlocal',
    'pause',
    'exit /b 0',
    '',
    ':KILL_PORT',
    'set "PORT=%~1"',
    'for /f "tokens=5" %%a in (\'netstat -ano ^| findstr ":%PORT% " ^| findstr "LISTENING"\') do (',
    '  echo   端口 %PORT% 被进程 %%a 占用，正在结束 ...',
    '  taskkill /PID %%a /F >nul 2>&1',
    ')',
    'goto :eof',
    '',
  ].join('\n'),
};

for (const [name, body] of Object.entries(files)) {
  const crlf = body.replace(/\r?\n/g, '\r\n');
  const buf = Buffer.from(crlf, 'utf8');
  const out = path.join(root, name);
  fs.writeFileSync(out, buf);
  console.log('wrote', out, buf.length, 'bytes');
}
